

** 3.4 Adaptation of Speaker Model
   GMM-UBM系统中, 我们主要通过 UBM模型 通过适应性修改参数, 
   使用Speaker的语音数据和一种Bayesian适应方法, 
   推导得到 假设Speaker的模型.
   
   不像计算UBM模型的标准方法, 计算某个Speaker的模型的方法,
   主要就是 通过适应方法 更新训练好的UBM的参数.
   
   这样计算的Speaker模型和 UBM模型, 会紧耦合.
   这样的性能 比 解耦和的方法更好, 并且能够更快的打分.
   
   Speaker模型的估计 也是类似EM算法, 
   1 EM算法的求 期望, 对speaker的语音信号进行重新估计 
   UBM的每个分模型.
   2 第二步, 将这些新的语音信号的统计估计 组合到 
   使用数据相关的混合参数方法得到的 UBM混合模型参数的旧的统计中,??
   
   数据相关混合参数 被设计为
   对最终Speaker模型的估计 
   对来自Speaker的具有较多数据的分模型 更依赖与新的数据统计
   而来自Speaker的具有较少数据的分模型 更依赖与旧的数据统计.


   
   计算公式, 以及更新公式
   
   使用数据相关的适应参数 允许混合分量的参数的调整. 如果一个混合分量 对于新数据
   具有一个低的概率总数ni, 那样会导致新数据权重减小, 然后对于原本旧数据的权重加
   强.
   
   相关因子 是一个控制 对一个分模型 应该有多少新数据来更新旧参数来生成新参数.


   NIST SRE 1996 的实验表明, 
   使用UBM 自适应实现的 Speaker model, 和 独立生成的Speaker Model
   有较大的提升, 
   一个合理的解释是 使用了自适应模型 在进行语音说话人识别时,
   不会被未见的声学事件影响.
   
   简单的说, 如果将UBM 考虑为覆盖了 说话人无关的特征空间, 
   以及发音的广泛声学类型, 
   那么适应性模型就是从说话人训练语音中提取到的 对发音声学模型 与说话人相关的调整
   
   那些在说话人训练语音中未提取到说话人相关特征的 混合分模型的那些参数
   只是从UBM中简单的拷贝了参数.

   这说明在识别时, 那些说话人训练数据 未出现的声学类别特征的 数据
   产生了近似于0的对数似然比率, 提供了一个整句 对特定说话人没什么影响. 既不利于也不影响.
   
   说话人模型的训练 只使用了该说话人的训练语音 会具有较低的似然值 
   对那些在训练数据中未出现的声学类别特征, 因此会产生较低的 似然比率值.
   就相当于 UBM 包含了 所有可能的 人相关声学类别特征, 而某些人具有某些特征并且是正相关或负相关, 不具有另外一些特征, 
   这样在训练调整UBM -> Speaker 时, 就会对应加重或减少某些特征值, 而对另一些特征分量(混合分模型)不影响.
   
   明显的, 当对一个 非 当前说话人的语音时, 会导致不正确的值.
   
   
   
