

#+TITLE: 文章标题
* 简单操作
** 正文标题
** 段落
段落一

段落二\\
段落三

** 字体
*粗体*
/斜体/
+删除线+
_下划线_
下标 H_2 O 
上标 E=mc^2
=等宽字体 samesize=

** 列表
   无序列表
   - list1
   - list2
   
     + list2-1
     + list2-2

   有序列表
   1. list1
   2. list2
      1) list2-1
      2) list2-2

   注意事项\\
   列表符号后面都要有空格\\
   同级别的列表缩进要相同\\
   如果想要加入同级别的列表，可以 M-RET\\
   空两行之后列表结束，如果空一行执行M-RET，实际上还是输入同级项\\
实例:\\
**** Lord of the Rings
   My favorite scenes are (in this order)
   1. The attack of the Rohirrim
   2. Eowyn's fight with the witch king
      + this was already my favorite scene in the book
      + I really like Miranda Otto.
   3. Peter Jackson being shot by Legolas
      - on DVD only
      He makes a really funny face when it happens.
ORG-LIST-END-MARKER
   But in the end, no individual scenes matter but the film as a whole.
   Important actors in this film are:
   - Elijah Wood :: He plays Frodo
   - Sean Austin :: He plays Sam, Frodo's friend.  I still remember
     him very well from his role as Mikey Walsh in The Goonies.
ORG-LIST-END-MARKER
  
** 嵌入元数据

*** 内容元数据
    org-mode 中包含以下几种
    s    #+begin_src ... #+end_src 
    e    #+begin_example ... #+end_example  : 单行的例子以冒号开头
    q    #+begin_quote ... #+end_quote      通常用于引用，与默认格式相比左右都会留出缩进
    v    #+begin_verse ... #+end_verse      默认内容不换行，需要留出空行才能换行
    c    #+begin_center ... #+end_center 
    l    #+begin_latex ... #+end_latex 
    L    #+latex: 
    h    #+begin_html ... #+end_html 
    H    #+html: 
    a    #+begin_ascii ... #+end_ascii 
    A    #+ascii: 
    i    #+index: line 
    I    #+include: line

    使用快捷键  <s Tab 即可

#+BEGIN_SRC  c -n -t -h 7 -w 40

int main(){
    printf("This is a test");
}


#+END_SRC



**** 表格与图片 

     对于表格和图片，可以在前面增加标题和标签的说明，以方便交叉引用。比如在表格的前面添加：\\
     # #+CAPTION: This is the caption for the next table (or link)\\
     则在需要的地方可以通过\\
     # ref{table1}\\
     来引用该表格。


**** 包含文件 
    当导出文档时，你可以包含其他文件中的内容。比如，想包含你的“.emacs”文件，你可以用：\\
    # #+INCLUDE: "~/.emacs" src emacs-lisp  \\
    可选的第二个第三个参数是组织方式（例如，“quote”，“example”，或者“src”），如果是 “src”，语言用来格式化内容。\\
    组织方式是可选的，如果不给出，文本会被当作 Org 模式的正常处理。用 C-c ,可以访问包含的文件。


*** 文档元数据
    具体的内容可以到文档中查看：Export options 我们除了手动添加上面的元数据外，还可以用快捷键 C-c C-e t 插入选项，其中可能有些选项我们需要经常用到：

    H:	标题层数
    num:	章节(标题)是否自动编号
    toc:	是否生成索引
    creator:	是否生成 "creat by emacs…"
    LINKUP:	UP: 链接
    LINKHOME:	HEME: 链接

    
    
** 表格
  
*** 建立和操作表格
    在 org mode 中，你可以画表格。方法很简单，在某一行顶格的位置输入’|'，然后输入表格第一行第一列的内容，再输入’|'，
    然后输入表格的的一行第二列的内容，以此类推。
    当第一行输入完成后，按 TAB， org mode 会把当前行对齐，然后为你创造出表格的下一行，让你继续输入。
    用 TAB 和 S+TAB可以在表格中正向或反向的移动。 

    比如下面的例子：
    #+CAPTION: 表格的标题
    | 1 | one                          |
    | 2 | two                          |
    | 3 | This is a long chunk of text |
    | 4 | four                         | 

    有时候，表格的某一项特别的长，你可以在任意一个表格的空白项内输入数字来限制其所在列的长度。比如：
    |   | <6>    |
    | 1 | one    |
    | 2 | two    |
    | 3 | This=> |
    | 4 | four   |

    在上面的例子中，第二列的长度不会超过6，超过的部分会被隐藏起来。你可以把鼠标移动到’This=>’上面，
    会有浮动标签显示出该项的内容，或者输入’C-c `’可以编辑被隐藏的内容。
    如果你发现表格的某一项没有如你预期的那样被隐藏起来，你可以在表格中的任意位置按 ‘C-c C-c’。 

    我们还可以把表格弄的更好看一些。在表格的某两行之间加入’|-’，然后按TAB，可以作出下面的效果：
    |   | <6>    |
    |---+--------|
    | 1 | one    |
    | 2 | two    |
    |---+--------|
    | 3 | This=> |
    | 4 | four   | 


*** 表格快捷键
    整体区域
    操作	说明
    C-c 竖线	创建或者转化成表格
    C-c C-c	调整表格，不移动光标
    TAB	移动到下一区域，必要时新建一行
    S-TAB	移动到上一区域
    RET	移动到下一行，必要时新建一行
    编辑行和列
    快捷键	说明
    M-LEFT/RIGHT	移动列
    M-UP/DOWN	移动行
    M-S-LEFT/RIGHT	删除/插入列
    M-S-UP/DOWN	删除/插入行
    C-c -	添加水平分割线
    C-c RET	添加水平分割线并跳到下一行
    C-c ^	根据当前列排序，可以选择排序方式


*** 表格中的计算
    例如一张价格表：
    
    数量	单价	总额
    2	3.45	 
    4	4.34	 
    5	3.44	 
    5	5.6	 
    在第二行第三列中输入'=$1*$2′。$1和$2表示第一列和第二列，在你自己的表格中，你会使用你希望的列数进行计算。
    | 数量 | 单价 |  总额 | test |       |
    |------+------+-------+------+-------|
    |    2 | 3.45 |   6.9 | 5.45 |   8.9 |
    |    4 | 4.34 | 17.36 | 8.34 | 21.36 |
    |    5 | 3.44 |  17.2 | 8.44 |  22.2 |
    |    5 |  5.6 |   28. | 10.6 |   33. |
    #+TBLFM: $3=$1*$2
    #+TBLFM: $4=$1+$2  
    #+TBLFM: $5=$1+$3
    使用方式 是直接 在表格后增加    #+TBLFM: $4=$1+$3 然后   C-c C-c 即可

    你可以输入’C-u C-c C-c’强制org mode为整个表格进行计算。
    如果你不想让某一列都按照公式计算，只希望在某一特定项上进行计算，你可以这样输入：':=$1*$2′, 即在等号前再加一个冒号。


** 连接
   在一个链接上按C-c C-o即可访问，至于调用什么程序访问，取决于链接的内容，emacs和org mode的配置了。
*** 自动连接
    对于符合链接规则的内容，org-mode会自动将其视为链接，包括括文件、网页、邮箱、新闻组、BBDB 数据库项、 IRC 会话和记录等。
    下面是一些例子：
    
    # http://www.astro.uva.nl/~dominik            on the web
    # file:/home/dominik/images/jupiter.jpg       file, absolute path
    # /home/dominik/images/jupiter.jpg            same as above
    # file:papers/last.pdf                        file, relative path
    # file:projects.org                           another Org file
    # docview:papers/last.pdf::NNN                open file in doc-view mode at page NNN
    # id:B7423F4D-2E8A-471B-8810-C40F074717E9     Link to heading by ID
    # news:comp.emacs                             Usenet link
    # mailto:adent@galaxy.net                     Mail link
    # vm:folder                                   VM folder link
    # vm:folder#id                                VM message link
    # wl:folder#id                                WANDERLUST message link
    # mhe:folder#id                               MH-E message link
    # rmail:folder#id                             RMAIL message link
    # gnus:group#id                               Gnus article link
    # bbdb:R.*Stallman                            BBDB link (with regexp)
    # irc:/irc.com/#emacs/bob                     IRC link
    # info:org:External%20links                   Info node link (with encoded space)

    # 对于文件链接，可以用::后面增加定位符的方式链接到文件的特定位置。定位符可以是行号或搜索选项。如：

    # file:~/code/main.c::255                     进入到 255 行
    # file:~/xx.org::My Target                    找到目标‘<<My Target>>’
    # file:~/xx.org/::#my-custom-id               查找自定义 id 的项

*** 手动连接
    [[link][description]]  \\[[link][description] ]
    [[link]]   \\[[link] ]

*** 内部连接
    内部链接就类似于HTML的锚点（实际上export成HTML文件后就变成了锚点），可以实现在一个文档内部的跳转。
    如下命令定义了一个名为target的跳转目标：
    
    #<<target>> 
    
    (这里我把锚点设置到*连接*这一部分开始处，大家可以点击下面效果中两个连接试试效果)
    如下方式可以设置到target的链接：
    [[target]] 或 [[target][猛击锚点]]

    
*** 其他常用的连接命令
    C-c l 可以在光标所在处创建一个跳转目标点，在需要跳转至该目标的位置输入命令C-c C-l可以建立到目标的链接
    当输入C-c C-l命令，光标若处在已经存在的一个链接上的时候，可以编辑改链接。
    命令C-c %可以记录当前光标所在位置，当光标移到其他地方后，可以用C-c &跳转回来。
    这里的位置记录类似一个 kill-ring，重复输入C-c %可以记录多个位置，重复输入C-c &可以连续跳转到之前记录的对应位置上。

    [[www.baidu.com][baidu]]
    
** 注脚
   在 org mode 中，你可以为你的文章添加注脚（footnote）。注脚的格式有两种，一是方括号+数字，二是方括号+fn+名字。比如下面有两个例子：在 org mode 的正文中写下这两句话：

   The Org homepage1 now looks a lot better than it used to. The Org homepage2 now looks a lot better than it used to.

   插入脚注：C-c C-x f 接下俩你可以写一些其他东西，然后在文章的末尾写上下面两句话（注意：必须要顶格[fn:1]写）：

[1] The link is: http://orgmode.org
[fn:orghome] The link is: http://orgmode.org
   把光标移动到正文的1处，按 C-c C-c，可以跳转到注脚1处，在注脚1处按 C-c C-c，可以跳转到正文的1 处。

** 分割线
   五条短线或以上显示为分隔线。
   -----




* 公式

org-mode 中使用的公式 是 mathjex, 兼容latex语法
  \begin{equation}  
  \sum\limits_{i=1}^n(单项评分_i * 权重)  
  \end{equation}  

  \sum\limits_{i=1}^n(单项评分_i * 权重)


  https://www.zybuluo.com/knight/note/96093

* 快捷键
** 折叠
   快捷键	说明
   S-TAB	循环切换整个文档的大纲状态（折叠、打开下一级、打开全部）
   TAB	循环切换光标所在的大纲状态

** 大纲或者列表之间移动
   快捷键	说明
   C-c C-n/p	移动到下上一个标题（不断标题是哪一级）
   C-c C-f/b	移动到同一级别的下/上标题
   C-c C-u	跳到上一级标题
   C-c C-j	切换到大纲预览状态

** 基于大纲/标题的编辑
   快捷键	说明
   M-RET	插入一个同级别的标题
   M-S-RET	插入一个同级别的TODO标题
   M-LEFT/RIGHT	将当前标题升/降级
   M-S-LEFT/RIGHT	将子树升/降级
   M-S-UP/DOWN	将子树上/下移动
   C-c *	将本行设为标题或者正文
   C-c C-w	将子树或者区域移动到另一个标题处（跨缓冲区）
   C-c C-x b	在新缓冲区显示当前分支
   C-c /	只列出包含搜索结果的大纲，并高亮，支持多种搜索方式




* 注意:
  使用如下方式, 可以禁用一些默认的结果, 例如角标 ^ 导出时 会直接变为上角标记, 可以用如下标记关闭.
  #+OPTIONS: ^:nil

* Footnotes

[fn:1] This is a Test.



[[https://www.cnblogs.com/holbrook/archive/2012/04/12/2444992.html][本文地址]]
[[http://www.cnblogs.com/holbrook/archive/2012/04/14/2447754.html][本文兄弟篇-Org-mode-任务管理]]

